# d-py-b, a simple python database by darkstarshine2011

from datetime import datetime
from os import makedirs
from ast import literal_eval

def GetDataBaseName(DataBaseFile):
    if DataBaseFile[-8:] == ".dpyb.py":
        pass
    elif DataBaseFile[-5:] == ".dpyb":
        DataBaseFile = f"{DataBaseFile}.py"
    elif DataBaseFile[-3:] == ".py":
        DataBaseFile = f"{DataBaseFile[:-3]}.dpyb.py"
    else:
        DataBaseFile = f"{DataBaseFile}.dpyb.py"
    return DataBaseFile

def CreateBackup(DataBaseFile):
    makedirs("Backup", exist_ok=True)
    LoadForBackup = open(GetDataBaseName(DataBaseFile), "r")
    BackupFile = open(f"Backup/{datetime.now().strftime("%Y%m%d_%H%M%S_%f")}.dpyb.py.backup", "w+")
    BackupFile.write(LoadForBackup.read())
    BackupFile.close()
    LoadForBackup.close()

def CreateDataBase(DataBaseFile):
    """
    creates a new database on the file name
    """
    DataBaseFile = GetDataBaseName(DataBaseFile)

    File = open(DataBaseFile, "w+")
    File.write("# a d-py-b database file, DO NOT EDIT THIS FILE\n# d-py-b, a simple python database by darkstarshine2011")
    File.close()

def AddTableToDataBase(DataBaseFile, TableName):
    """
    adds a new table into the database
    """
    CreateBackup(DataBaseFile)
    DBData = open(GetDataBaseName(DataBaseFile), "r").read()
    if f"\n{TableName} =" not in DBData and f"\n{TableName}=" not in DBData:
        DBFile = open(GetDataBaseName(DataBaseFile), "a")
        DBFile.write(f"""\n\n# ---\n\n{TableName} = {{1:{{1:""}}}}""")
        DBFile.close()

def AddRow(DataBaseFile, TableName, Rows): # Debuged by DeepSeek :)
    """
    adds a row into the table
    """
    CreateBackup(DataBaseFile)

    Name = GetDataBaseName(DataBaseFile)
    File = open(Name, "r")
    Lines = File.readlines()
    File.close()

    Prefix = f"{TableName} = "
    for i in range(len(Lines)):
        if Lines[i].startswith(Prefix):
            Table = literal_eval(Lines[i][len(Prefix):].strip())
            NewID = (max(Table.keys()) + 1) if Table else 1
            Table[NewID] = Rows
            Lines[i] = f"{TableName} = {Table}\n"
            break

    File = open(Name, "w")
    File.writelines(Lines)
    File.close()


def AddColumn(DataBaseFile, TableName, DefaultValue=""): # This function is created by DeepSeek, Because I was too lazy to do it :/ ... I mean who the f*ck cares? it just works :///
    """
    adds a new column to every row of the table
    DefaultValue: مقدار پیش‌فرض برای خونه‌های جدید
    Returns the new column id
    """
    CreateBackup(DataBaseFile)

    Name = GetDataBaseName(DataBaseFile)
    File = open(Name, "r")
    Lines = File.readlines()
    File.close()

    Prefix = f"{TableName} = "
    for i in range(len(Lines)):
        if Lines[i].startswith(Prefix):
            Table = literal_eval(Lines[i][len(Prefix):].strip())

            # پیدا کردن بزرگ‌ترین شماره ستون موجود
            MaxCol = 0
            for RowID in Table:
                for ColID in Table[RowID]:
                    if ColID > MaxCol:
                        MaxCol = ColID
            NewCol = MaxCol + 1

            # اضافه کردن ستون جدید به همه‌ی ردیف‌ها
            for RowID in Table:
                Table[RowID][NewCol] = DefaultValue

            Lines[i] = f"{TableName} = {Table}\n"
            break

    File = open(Name, "w")
    File.writelines(Lines)
    File.close()


def WriteData(DataBaseFile, TableName, Row, Column):
    pass

def ReadData(DataBaseFile, TableName, Row, Column):
    pass